### ISSUE TITLE
Ta bort siffrorna i början av diagnosnamnen i parametern

### ISSUE THREAD

**Issue by eribul** [eribul/HH_koll_pa_laget#12]

**Comment by eribul** [comment]
Vi avvaktar detts då dessa namn också används i INCA:s urvalsdialog och det där är svårare att använda subsets. Skulle kräva att jag gör hela urvalet i R men då får vi nackdelen att det kan ta längre tid. Avvaktar!

**Comment by Cstaf** [comment]
Erik H anser inte att detta är en prioritet. (Sitter och demoar Github i Sigtuna).
