### ISSUE TITLE
Rubrik för sidhuvudet

### ISSUE THREAD

**Issue by eribul** [eribul/HH_koll_pa_laget#2]
Mail från Erik H 2015-09-30:

> Vi behöver mera tydligt ange vad de första siffrorna står för. En rubrik vore bra. T ex "Inrapporteringsaktivitet under 2015”. Den kan ligga ovanför där namnet på den egna enheten ligger.

**Comment by Cstaf** [comment]
Jag håller på och gör denna justering för Gyn. Har lagt in:         "document.getElementById("inrapp").innerHTML = "Inrapporteringsaktivitet under " + år;" sedan skapar jag en div och lägger ovanför anropet till sjukhusnamnet. Blir bra, dock osäker vilken class som är bäst till denna rubrik.

**Comment by eribul** [comment]
Fick nu önskemål om en snabb lösning at ev kunna presentera redan idag kl 13. 
Blev därmed att jag bara la in som en del av den befintliga rubriken. Men på längre sikt vore det förstås bättre att göra de mer ordentligt.
